export const dataSample = [
    {
        dateTime: "2/18/2024 4:26:33 PM",
        roundCount: 1,
        drawCount: 0,
        playerOne: "d",
        playerOneWinCount: 0,
        playerOneLoseCount: 0,
        playerTwo: "dd",
        playerTwoWinCount: 0,
        playerTwoLoseCount: 0,
    },
    {
        dateTime: "2/18/2024 5:15:22 PM",
        roundCount: 3,
        drawCount: 1,
        playerOne: "Ella",
        playerOneWinCount: 2,
        playerOneLoseCount: 1,
        playerTwo: "Max",
        playerTwoWinCount: 1,
        playerTwoLoseCount: 2,
    },
    {
        dateTime: "2/18/2024 6:45:09 PM",
        roundCount: 4,
        drawCount: 3,
        playerOne: "Sarah",
        playerOneWinCount: 1,
        playerOneLoseCount: 2,
        playerTwo: "Tom",
        playerTwoWinCount: 2,
        playerTwoLoseCount: 1,
    },
    {
        dateTime: "2/18/2024 8:30:17 PM",
        roundCount: 5,
        drawCount: 2,
        playerOne: "Chris",
        playerOneWinCount: 1,
        playerOneLoseCount: 3,
        playerTwo: "Olivia",
        playerTwoWinCount: 3,
        playerTwoLoseCount: 1,
    },
    {
        dateTime: "2/18/2024 9:20:58 PM",
        roundCount: 6,
        drawCount: 0,
        playerOne: "David",
        playerOneWinCount: 3,
        playerOneLoseCount: 2,
        playerTwo: "Sophia",
        playerTwoWinCount: 2,
        playerTwoLoseCount: 3,
    },
    {
        dateTime: "2/18/2024 10:10:42 PM",
        roundCount: 3,
        drawCount: 1,
        playerOne: "Emma",
        playerOneWinCount: 2,
        playerOneLoseCount: 1,
        playerTwo: "William",
        playerTwoWinCount: 1,
        playerTwoLoseCount: 2,
    },
    {
        dateTime: "2/18/2024 11:05:33 PM",
        roundCount: 4,
        drawCount: 2,
        playerOne: "Liam",
        playerOneWinCount: 4,
        playerOneLoseCount: 0,
        playerTwo: "Ava",
        playerTwoWinCount: 0,
        playerTwoLoseCount: 4,
    },
    {
        dateTime: "2/18/2024 11:59:12 PM",
        roundCount: 5,
        drawCount: 3,
        playerOne: "Noah",
        playerOneWinCount: 1,
        playerOneLoseCount: 2,
        playerTwo: "Mia",
        playerTwoWinCount: 2,
        playerTwoLoseCount: 1,
    },
    {
        dateTime: "2/19/2024 12:30:28 AM",
        roundCount: 6,
        drawCount: 0,
        playerOne: "James",
        playerOneWinCount: 2,
        playerOneLoseCount: 3,
        playerTwo: "Charlotte",
        playerTwoWinCount: 3,
        playerTwoLoseCount: 2,
    },
    {
        dateTime: "2/19/2024 1:45:19 AM",
        roundCount: 3,
        drawCount: 1,
        playerOne: "Logan",
        playerOneWinCount: 2,
        playerOneLoseCount: 1,
        playerTwo: "Amelia",
        playerTwoWinCount: 1,
        playerTwoLoseCount: 2,
    }
];
